openapi: 3.1.0
info:
  version: 0.0.1
  title: Leagueify Roster API
  summary: Open Source Sporting League Platform.
  description: '
    The Leagueify roster is responsible for managing user
    authentication, authorization, and profiles.
    '
  license:
    name: MIT
    url: https://raw.githubusercontent.com/Leagueify/roster/main/LICENSE
  contact:
    name: Leagueify Support
    url: https://github.com/Leagueify/roster/issues

servers:
  - url: http://localhost:6504/roster
    description: Local Docker Development

paths:
  /healthz:
    get:
      tags:
      - Health Check
      summary: Roster Service Health Check
      description: '
        Check the health status of the Leagueify Roster service. This endpoint
        should return the service name and a status of ok.
        '
      responses:
        200:
          description: Health Check Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  service:
                    description: Service Name
                    type: string
                    example: roster
                  status:
                    description: Server HTTP Status
                    type: string
                    example: ok
